-- --------------------------------------------------
--   Cloud  &  User
-- --------------------------------------------------
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 61, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 201, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 176, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 46, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 24, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 165, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 112, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 78, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 192, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 195, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 196, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 148, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 226, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 123, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 89, 0, 1, 1, now(), now());
INSERT INTO currency_country (currency_id, country_id, eu, create_user_id, update_user_id, create_time, update_time) VALUES(',1,', 168, 0, 1, 1, now(), now());

-- --------------------------------------------------
--   Cloud  &  Payment
-- --------------------------------------------------
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('CUB', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('PRK', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('SYR', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('RUS', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('BLR', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('VEN', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('MYA', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('ZIM', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('CAF', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('COD', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('CGO', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('SUD', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('SSD', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('NCA', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('LIB', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');
INSERT INTO country_pay_config (country_code, min_deposit, max_balance, min_withdrawal, create_time, create_user_id, update_time, update_user_id, del, currency) VALUES('UKR', 0.00, 0.00, 0.00, '2025-03-12 11:57:54', 1, '2025-03-12 11:57:54', 1, 0, 'USD');

